const mysql = require('mysql2/promise');
const nodemailer = require('nodemailer');
let pool;
function json(res,status,payload){res.statusCode=status;res.setHeader('content-type','application/json; charset=utf-8');res.setHeader('cache-control','no-store');res.end(JSON.stringify(payload));}
function clean(value,max){return typeof value==='string'?value.trim().slice(0,max):'';}
function trpcOk(value){return [{result:{data:{json:value}}}];}
function trpcError(message,code='INTERNAL_SERVER_ERROR'){return [{error:{json:{message,code,data:{code}}}}];}
function inputOf(body){if(Array.isArray(body))return body[0]?.json||{};if(body&&body[0])return body[0].json||{};return body?.json||body||{};}
async function getPool(){if(!process.env.DATABASE_URL)throw new Error('DATABASE_URL 환경변수가 설정되지 않았습니다.');if(!pool)pool=mysql.createPool(process.env.DATABASE_URL);return pool;}
async function sendNotification(data){if(!process.env.CONTACT_EMAIL||!process.env.GMAIL_USER||!process.env.GMAIL_APP_PASSWORD){console.warn('[Email] Gmail 환경변수가 없어 메일을 건너뜁니다.');return false;}const transporter=nodemailer.createTransport({service:'gmail',auth:{user:process.env.GMAIL_USER,pass:process.env.GMAIL_APP_PASSWORD}});const configured=(process.env.CONTACT_EMAIL||'').split(',').map(value=>value.trim()).filter(Boolean);const recipients=[...new Set(['qudrb9382@naver.com','dksk0359@gmail.com',...configured])];const source=data.source||'직접 접속';const medium=data.medium||'direct';const html='<h2>새로운 공연 문의가 접수되었습니다</h2><p><b>기관명:</b> '+escapeHtml(data.organization)+'</p><p><b>연락처:</b> '+escapeHtml(data.phone)+'</p><p><b>공연:</b> '+escapeHtml(data.performance||'미선택')+'</p><p><b>희망 날짜:</b> '+escapeHtml(data.date||'미정')+'</p><p><b>문의 내용:</b><br>'+escapeHtml(data.message).replace(/\n/g,'<br>')+'</p><p><b>유입:</b> '+escapeHtml(source)+' ('+escapeHtml(medium)+')</p>';await transporter.sendMail({from:'비버컴퍼니 <'+process.env.GMAIL_USER+'>',to:recipients,subject:'[비버컴퍼니] 새 문의 - '+data.organization,html});return true;}
function escapeHtml(value){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
async function submit(data){const organization=clean(data.organization,255),phone=clean(data.phone,20),performance=clean(data.performance,100),date=clean(data.date,50),message=clean(data.message,10000),source=clean(data.source,100),medium=clean(data.medium,50),campaign=clean(data.campaign,100),referrerUrl=clean(data.referrerUrl,2000);if(!organization)throw new Error('기관명을 입력해주세요');if(!phone)throw new Error('연락처를 입력해주세요');if(!message)throw new Error('문의 내용을 입력해주세요');let id=null;if(process.env.DATABASE_URL){const db=await getPool();const [result]=await db.execute('INSERT INTO consultations (organization, phone, performance, date, message, source, medium, campaign, referrerUrl, status) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, \'pending\')',[organization,phone,performance||null,date||null,message,source||null,medium||null,campaign||null,referrerUrl||null]);id=Number(result.insertId);}const sent=await sendNotification({organization,phone,performance,date,message,source,medium,campaign,referrerUrl});if(!sent)throw new Error('Gmail 발송 환경변수가 설정되지 않았습니다.');return {success:true,consultationId:id,emailSent:true};}
function decodeXml(value){return String(value||'').replace(/<!\[CDATA\[|\]\]>/g,'').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&#39;/g,"'").trim();}
function xmlTag(block,tag){const m=block.match(new RegExp('<'+tag+'(?:\\s[^>]*)?>([\\s\\S]*?)</'+tag+'>','i'));return decodeXml(m?m[1]:'');}
async function blogPosts(){try{const r=await fetch('https://rss.blog.naver.com/eunji6043.xml',{headers:{'user-agent':'Mozilla/5.0'}});if(!r.ok)return[];const xml=await r.text();const blocks=[...xml.matchAll(/<item(?:\s[^>]*)?>([\s\S]*?)<\/item>/gi)].map(m=>m[1]);return blocks.slice(0,20).map(block=>{const raw=xmlTag(block,'description');const img=(raw.match(/<img[^>]+src=["']([^"']+)/i)||[,''])[1]||((raw.match(/https?:\/\/(?:blogthumb|phinf)\.pstatic\.net[^\s<>"']+/i)||[])[0]||'');return{title:xmlTag(block,'title'),link:xmlTag(block,'link'),pubDate:xmlTag(block,'pubDate'),description:xmlTag(block,'description').replace(/<[^>]+>/g,'').replace(/\s+/g,' ').slice(0,200),category:xmlTag(block,'category'),thumbnail:img}})}catch(error){console.error('[Blog]',error);return[]}}
function ytDecode(value){return String(value||'').replace(/\u([0-9a-f]{4})/gi,(_,hex)=>String.fromCharCode(parseInt(hex,16))).replace(/\n/g,' ').replace(/\\"/g,'"');}
function ytField(block,pattern){const m=block.match(pattern);return m?ytDecode(m[1]):'';}
async function youtubeVideos(){try{const r=await fetch('https://www.youtube.com/@비버선생님-f9i/videos?hl=ko',{headers:{'user-agent':'Mozilla/5.0','accept-language':'ko-KR,ko;q=0.9'}});if(!r.ok)return[];const html=await r.text();const ids=[];for(const m of html.matchAll(/"videoId":"([A-Za-z0-9_-]{11})"/g)){if(!ids.includes(m[1]))ids.push(m[1]);if(ids.length>=8)break;}return ids.map(id=>{const idx=html.indexOf('"videoId":"'+id+'"');const chunk=html.slice(idx,idx+16000);const title=ytField(chunk,/"title":\{"content":"([^"]*)"/)||ytField(chunk,/"title":\{"runs":\[\{"text":"([^"]*)"/);const publishedAt=ytField(chunk,/"publishedTimeText":\{"simpleText":"([^"]*)"/);return{id,title:title||'비버선생님 최신 영상',description:'비버선생님 YouTube 최신 영상',url:'https://www.youtube.com/watch?v='+id,thumbnail:'https://i.ytimg.com/vi/'+id+'/hqdefault.jpg',publishedAt}}).filter(video=>video.id&&video.title)}catch(error){console.error('[YouTube]',error);return[]}}
async function handler(req,res){const url=new URL(req.url||'/', 'https://beavercompany.co.kr');if(req.method==='OPTIONS'){res.statusCode=204;return res.end();}if(url.searchParams.get('route')==='blog')return json(res,200,await blogPosts());if(url.searchParams.get('route')==='youtube')return json(res,200,await youtubeVideos());if(url.searchParams.get('route')!=='trpc')return json(res,404,{error:'Not found'});if(req.method!=='POST')return json(res,405,trpcError('POST 요청만 허용됩니다.','METHOD_NOT_SUPPORTED'));try{const chunks=[];for await(const chunk of req)chunks.push(chunk);const body=JSON.parse(Buffer.concat(chunks).toString('utf8')||'{}');return json(res,200,trpcOk(await submit(inputOf(body))));}catch(error){const message=error instanceof Error?error.message:'문의 접수에 실패했습니다.';console.error('[Consultation]',message);return json(res,500,trpcError(message));}}
module.exports=handler;
